spring:
  application:
      name: movie-micro-service
   
  datasource:
    url: jdbc:mysql://localhost:3306/security1
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: bhiShma#89
     
  jpa:
    show-sql: true
    hibernate:
       ddl-auto: update
    properties:
       hibernate:
         format_sql: true 

server:
   port: 7171
